id: f777f38d9a4f4cc284f93ab423f50ab6
initial_creation_type: ocr
source_metadata:
  volumes:
    57dce434d6bf49c4acf020f4c009eb08:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ''
      total_pages: 1539
      volume_number: 1
